Add taint parameter and change rules
Ostorlab/ostorlab_insecure_android_app pull request #29
Opened 2024-01-24 16:47 UTC by ErebusZ

2024-01-24 16:54 UTC, mohsinenar approved these changes

2024-01-24 17:54 UTC, 3asm requested changes

2024-01-24 17:54 UTC, 3asm commented on app/src/main/java/co/ostorlab/insecure_app/MainActivity.java
> +                executeAllRules(user_input);
Should come from an intent to make it dangerous.

2024-01-24 17:54 UTC, 3asm commented on app/src/main/java/co/ostorlab/insecure_app/bugs/calls/WebviewInsecureSettings.java
> +            if (user_input.length() != 0){
isEmpty instead of length() != 0.

2024-01-25 18:24 UTC, 3asm requested changes

2024-01-25 18:24 UTC, 3asm commented on app/src/main/java/co/ostorlab/insecure_app/MainActivity.java
> +        }
And the rules. Why are the rules not executed here as well with default input.

2024-01-25 18:24 UTC, 3asm commented on app/src/main/java/co/ostorlab/insecure_app/MainActivity.java
> +            user_input = "";
Inline user_input in this case.

2024-01-26 08:44 UTC, amine3 approved these changes

2024-01-26 12:31 UTC, 3asm approved these changes

2024-01-26 12:31 UTC, merged