Add bind rule to the flutter App
Ostorlab/ostorlab_insecure_android_app pull request #35
Opened 2024-09-23 12:23 UTC by ErebusZ

This PR adds a bug rule for the method Bind, this should trigger an open port on device finding.

2024-09-23 15:09 UTC, ohachimOs commented
`bind` fails so we catch the error to avoid crash? can we maybe attempt to bind to another port? or just wait a bit a try again, sometimes there is a bit of lag with the `TIME_WAIT` state, if the port was recently bind to something (it could be the same app that had just closed), is it not worth it to try in this use case?
Also can you add a description

2024-09-23 15:36 UTC, ErebusZ commented
> TIME_WAIT

That is a little bit behind the point of the app, this code is meant for testing the platform detection ability. invoking bind with vulnerable args is enough to that.

2024-09-23 17:49 UTC, 3asm commented
@ErebusZ please add a description.

2024-09-23 17:50 UTC, 3asm requested changes

2024-09-23 17:50 UTC, 3asm commented on ostorlab_insecure_flutter_app/lib/bugs/bind.dart
> +class OpenPortOnDevice extends BugRule {
I would rather have it name BindRule, I would know what it does.

2024-09-24 07:58 UTC, ErebusZ commented
> @ErebusZ please add a description.

Added.

2024-09-24 09:36 UTC, 3asm approved these changes

2024-09-24 09:36 UTC, 3asm commented on ostorlab_insecure_flutter_app/lib/bugs/bind.dart
> +    var port = (input != "") ? int.parse(input) : 450;
```suggestion
    var port = (input != "") ? int.parse(input) : 4450;
```

2024-09-24 09:58 UTC, merged